version: '3.10'

services:
  web:
    build: .
    ports:
      - "8083:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:rootpassword@db/payment_gateway
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - .:/app  # Mount the current directory (your project root) to /app in the container

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=payment_gateway
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: