name: CI - Build and Push

on:
  push:
    branches:
      - main

jobs:
  test-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install API dependencies
        working-directory: ./payment-gateway
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API unit tests
        working-directory: ./payment-gateway
        run: |
          pytest -s -v # or your test command

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push client image using docker-compose
        working-directory: ./payment-gateway-client
        run: |
          docker build -t kagsburg/payment-gateway-client .
          docker push kagsburg/payment-gateway-client

      - name: Build and push API image using docker-compose
        working-directory: ./payment-gateway
        run: |
          docker build -t kagsburg/payment-gateway-api .
          docker push kagsburg/payment-gateway-api
